# Generated by Django 5.0.4 on 2024-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbauthor', '0002_alter_assignment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='seq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(max_length=32),
        ),
    ]
