# Generated by Django 5.0.4 on 2024-04-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbauthor', '0003_assignment_course_assignment_seq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.CharField(default='siads505', max_length=32),
            preserve_default=False,
        ),
    ]
